module piestrak_sorting_network_5(input [4:0] x, output maj);
  wire sort_c0_and, sort_c0_or, sort_c10_and, sort_c10_or, sort_c11_and, sort_c11_or, sort_c12_and, sort_c12_or, sort_c13_and, sort_c13_or, sort_c14_and, sort_c14_or, sort_c15_and, sort_c15_or, sort_c16_and, sort_c16_or, sort_c17_and, sort_c17_or, sort_c18_and, sort_c18_or, sort_c19_and, sort_c19_or, sort_c1_and, sort_c1_or, sort_c20_and, sort_c20_or, sort_c21_and, sort_c21_or, sort_c22_and, sort_c22_or, sort_c23_and, sort_c23_or, sort_c2_and, sort_c2_or, sort_c3_and, sort_c3_or, sort_c4_and, sort_c4_or, sort_c5_and, sort_c5_or, sort_c6_and, sort_c6_or, sort_c7_and, sort_c7_or, sort_c8_and, sort_c8_or, sort_c9_and, sort_c9_or;
  assign sort_c0_or = x[0] | x[1];
  assign sort_c0_and = x[0] & x[1];
  assign sort_c1_or = x[2] | x[3];
  assign sort_c1_and = x[2] & x[3];
  assign sort_c2_or = sort_c0_or | sort_c1_and;
  assign sort_c2_and = sort_c0_or & sort_c1_and;
  assign sort_c3_or = sort_c0_and | sort_c1_or;
  assign sort_c3_and = sort_c0_and & sort_c1_or;
  assign sort_c4_or = sort_c2_or | sort_c3_or;
  assign sort_c4_and = sort_c2_or & sort_c3_or;
  assign sort_c5_or = sort_c2_and | sort_c3_and;
  assign sort_c5_and = sort_c2_and & sort_c3_and;
  assign sort_c6_or = x[4] | 1'b0;
  assign sort_c6_and = x[4] & 1'b0;
  assign sort_c7_or = 1'b0 | 1'b0;
  assign sort_c7_and = 1'b0 & 1'b0;
  assign sort_c8_or = sort_c6_or | sort_c7_and;
  assign sort_c8_and = sort_c6_or & sort_c7_and;
  assign sort_c9_or = sort_c6_and | sort_c7_or;
  assign sort_c9_and = sort_c6_and & sort_c7_or;
  assign sort_c10_or = sort_c8_and | sort_c9_and;
  assign sort_c10_and = sort_c8_and & sort_c9_and;
  assign sort_c11_or = sort_c8_or | sort_c9_or;
  assign sort_c11_and = sort_c8_or & sort_c9_or;
  assign sort_c12_or = sort_c4_or | sort_c10_and;
  assign sort_c12_and = sort_c4_or & sort_c10_and;
  assign sort_c13_or = sort_c4_and | sort_c10_or;
  assign sort_c13_and = sort_c4_and & sort_c10_or;
  assign sort_c14_or = sort_c5_or | sort_c11_and;
  assign sort_c14_and = sort_c5_or & sort_c11_and;
  assign sort_c15_or = sort_c5_and | sort_c11_or;
  assign sort_c15_and = sort_c5_and & sort_c11_or;
  assign sort_c16_or = sort_c12_or | sort_c14_or;
  assign sort_c16_and = sort_c12_or & sort_c14_or;
  assign sort_c17_or = sort_c13_or | sort_c15_or;
  assign sort_c17_and = sort_c13_or & sort_c15_or;
  assign sort_c18_or = sort_c16_or | sort_c17_or;
  assign sort_c18_and = sort_c16_or & sort_c17_or;
  assign sort_c19_or = sort_c16_and | sort_c17_and;
  assign sort_c19_and = sort_c16_and & sort_c17_and;
  assign sort_c20_or = sort_c12_and | sort_c14_and;
  assign sort_c20_and = sort_c12_and & sort_c14_and;
  assign sort_c21_or = sort_c13_and | sort_c15_and;
  assign sort_c21_and = sort_c13_and & sort_c15_and;
  assign sort_c22_or = sort_c20_or | sort_c21_or;
  assign sort_c22_and = sort_c20_or & sort_c21_or;
  assign sort_c23_or = sort_c20_and | sort_c21_and;
  assign sort_c23_and = sort_c20_and & sort_c21_and;
  assign maj = sort_c19_or;
endmodule

module fa(input a, b, cin, output sum, cout);
  assign sum = a ^ b ^ cin;
  assign cout = (a & b) | (a & cin) | (b & cin);
endmodule
